### ISSUE TITLE
capstone integration?

### ISSUE THREAD

**Issue by krytarowski** [ryo/aarch64dis#1]
Could we integrate capstone for this task?

**Comment by ryo** [comment]
Of course! this code is BSD lisenced.

**Comment by krytarowski** [comment]
Rationale for closing? Abandoned?

**Comment by krytarowski** [comment]
Just being curious.

**Comment by ryo** [comment]
eh...

>Could we integrate capstone for this task?

"We" you said means "you and me" ? I misunderstood "We" means "you and others".

I don't know well about status of capstone project, What should I do?

**Comment by krytarowski** [comment]
I see, I was just curious. I recall that someone tried to integrate capstone for a similar task into some kernel. It's not needed to do anything on your own. I wondered whether adding a homegrown diasm might be a lot of work and reusing something that is ready could solve it immediately.

Thanks anyway!
